### ISSUE TITLE
Can't Get Rotate to Work

### ISSUE THREAD

**Issue by rylancole** [TWew/CADLikeOrbit_Camera#1]
I followed the instructions on the Godot Asset Library page to install the plug-in and was able to get 'Zooming' and 'Panning' to work, but nothing for 'Rotating'. I tried switching to each of 'Right Click', 'Middle Click', and 'Left Click' for the event and none worked. Double-triple checked my spelling. Deleted and re-added the actions. Reset Godot. Any other suggestions?

**Comment by TWew** [comment]
Hello,
there is an option "RotateUsingZoomPlusPan" in the Camera-Settings. by default it is Checked.
If this option is Checked you can rotate by pressing the buttons for Zooming and Panning at the same time. If it is unchecked the Rotating Action from the Key-Mapping is used.
